name: LibCmo macOS Build

on: [workflow_dispatch]

jobs:
  macos-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Fetch YYCCommonplace
      uses: actions/checkout@v4
      with:
        repository: 'yyc12345/YYCCommonplace'
        ref: 'master'
        path: 'extern/YYCCommonplace'
    - name: Build YYCCommonplace
      shell: bash
      run: |
        cd extern/YYCCommonplace
        chmod +x ../../.github/scripts/yycc-macos.sh
        source ../../.github/scripts/yycc-macos.sh
        echo "YYCCommonplace_ROOT=$YYCCommonplace_ROOT" >> "$GITHUB_ENV"
        cd ../..
    - name: Fetch ZLIB
      uses: actions/checkout@v4
      with:
        repository: 'madler/zlib'
        ref: 'v1.3.1'
        path: 'extern/zlib'
    - name: Build ZLIB
      shell: bash
      run: |
        cd extern/zlib
        chmod +x ../../.github/scripts/zlib-macos.sh
        source ../../.github/scripts/zlib-macos.sh
        echo "ZLIB_ROOT=$ZLIB_ROOT" >> "$GITHUB_ENV"
        cd ../..
    - name: Fetch STB
      uses: actions/checkout@v4
      with:
        repository: 'nothings/stb'
        ref: '2e2bef463a5b53ddf8bb788e25da6b8506314c08'
        path: 'extern/stb'
    - name: Build STB
      shell: bash
      run: |
        cd extern/stb
        chmod +x ../../.github/scripts/stb-macos.sh
        source ../../.github/scripts/stb-macos.sh
        echo "STB_ROOT=$STB_ROOT" >> "$GITHUB_ENV"
        cd ../..
    - name: Build LibCmo
      shell: bash
      run: |
        chmod +x ./.github/scripts/macos.sh
        ./.github/scripts/macos.sh
    - name: Upload Built Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibCmo-macos-build
        path: bin/install/*
        retention-days: 30        